version: '3.7'
services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    environment:
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=Oracle_123
      - APP_USER=test
      - APP_USER_PASSWORD=1234
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup
      - ./sql/setup:/opt/oracle/scripts/startup
    networks:
      - oracle-php
  
  php:
    build: ./php
    container_name: php-app
    environment:
      - PHP_MEMORY_LIMIT=512M
    ports:
      - "8080:80"
    volumes:
      - ./php/src:/var/www/html
    depends_on:
      - oracle-db
    networks:
      - oracle-php



volumes:
  oracle-data:
  oracle-backup:

networks:
  oracle-php: