version: '3.7'
services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    environment:
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=Oracle_123
      - APP_USER=test
      - APP_USER_PASSWORD=1234
    ports:
      - 1521:1521
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup
      - ./setup:/opt/oracle/scripts/startup
    # healthcheck:
    #   test: ["CMD", "sqlplus", "-L", "sys/Oracle_123@//localhost:1521/ORCLCDB as sysdba", "@healthcheck.sql"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5

volumes:
  oracle-data:
  oracle-backup: